In [1]:
import pandas as pd

In [2]:
nba = pd.read_csv("../data/nba_2017_br.csv")

In [3]:
nba.describe()

,Rk,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PS/G
count,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,485.000000,486.000000,486.000000,...,471.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000
mean,243.500000,26.405350,53.781893,25.308642,19.900206,3.120165,6.913992,0.441278,0.768107,2.184568,...,0.741155,0.851440,2.715226,3.565226,1.830247,0.625309,0.392593,1.098148,1.680247,8.426749
std,140.440379,4.345194,24.838733,28.715875,9.059629,2.158294,4.524459,0.099083,0.755537,1.941757,...,0.139453,0.759536,1.801779,2.428492,1.766110,0.410679,0.417438,0.781551,0.737494,6.057949
min,1.000000,19.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,122.250000,23.000000,35.250000,1.000000,12.800000,1.500000,3.625000,0.399000,0.125000,0.600000,...,0.675000,0.300000,1.400000,1.900000,0.600000,0.300000,0.100000,0.500000,1.200000,4.125000
50%,243.500000,26.000000,62.500000,11.000000,19.100000,2.500000,5.900000,0.442000,0.600000,1.800000,...,0.766000,0.600000,2.400000,3.000000,1.200000,0.500000,0.300000,0.900000,1.700000,6.800000
75%,364.750000,29.000000,75.000000,49.750000,27.000000,4.200000,9.175000,0.485000,1.200000,3.400000,...,0.832000,1.200000,3.500000,4.700000,2.300000,0.900000,0.500000,1.400000,2.200000,10.975000
max,486.000000,40.000000,82.000000,82.000000,37.800000,10.300000,24.000000,1.000000,4.100000,10.000000,...,1.000000,4.300000,10.300000,14.100000,11.200000,2.000000,3.000000,5.700000,3.900000,31.600000

SyntaxError: invalid syntax (<ipython-input-6-4b6f74841ce0>, line 1)