In [1]:
import pandas as pd

In [2]:
nba_pie = pd.read_csv("../data/nba_2017_pie.csv")

In [4]:
nba_pie.describe()

,AGE,GP,W,L,MIN,OFFRTG,DEFRTG,NETRTG,AST%,AST/TO,AST RATIO,OREB%,DREB%,REB%,TO RATIO,EFG%,TS%,USG%,PACE,PIE
count,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000,486.000000
mean,26.847737,53.781893,26.870370,26.911523,19.899588,103.924897,106.002469,-2.074074,13.316667,1.535021,16.044650,5.003909,15.248148,10.078395,10.571811,49.245473,52.587037,18.614609,98.269609,8.625514
std,4.355997,24.838733,15.577994,14.272257,9.060969,8.883965,7.493152,9.752573,9.091520,0.857071,8.337648,4.299921,7.339796,5.083578,4.134941,10.023145,9.279085,5.491156,3.577507,3.830067
min,19.000000,1.000000,0.000000,1.000000,0.800000,0.000000,0.000000,-58.700000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,58.060000,-6.100000
25%,24.000000,35.250000,15.000000,16.000000,12.725000,102.000000,103.525000,-5.875000,6.800000,0.980000,9.800000,1.900000,10.425000,6.300000,8.300000,46.600000,50.200000,14.700000,96.697500,6.625000
50%,26.000000,62.500000,27.000000,28.000000,19.100000,104.600000,106.300000,-1.400000,10.100000,1.480000,14.200000,3.500000,13.900000,8.900000,10.200000,50.050000,53.700000,18.300000,98.190000,8.500000
75%,30.000000,75.000000,38.000000,37.000000,27.000000,107.700000,108.700000,2.600000,18.150000,2.000000,21.075000,7.475000,19.000000,12.950000,12.300000,53.600000,57.575000,21.575000,100.155000,10.600000
max,40.000000,82.000000,66.000000,59.000000,37.800000,130.800000,140.000000,46.900000,54.300000,6.330000,51.500000,37.500000,100.000000,50.000000,30.000000,100.000000,79.900000,41.400000,109.870000,23.000000